export const FETCH_CRYPTO_DATA = "FETCH_CRYPTO_DATA";
export const LOADING_START_ON_DATA_FETCH = "LOADING_START_ON_DATA_FETCH";
export const LOADING_END_AFTER_DATA_FETCH = "LOADING_END_AFTER_DATA_FETCH";
